### PR TITLE
new eat Packages page in navbar

### PR DESCRIPTION
**Pull request by grewered**

### CODE REVIEW

**Comment by grewered** [comment]
error due to something to do with the library, I think.

**Comment by grewered** [comment]
comments from the old pull request: 

grafik

grafik

**Comment by grewered** [comment]
to do:

- [ ] naming multiple authors
- [ ] with links to their profiles?

**Comment by grewered** [comment]
https://iqb-research.github.io/IQB-Methods/posts_eat.html
there's still the problem that as soon as a pull request's checks pass, the changes are shown on the website. but when they fail, they don't.
but it definitely works now, finally!

**Comment by nickhaf** [comment]
Looks great, exactly what we had in mind! Please merge!

**Pull request merged**
