### PR TITLE
learn page: multiple listings

### PR DESCRIPTION
**Pull request by grewered**

### CODE REVIEW

**Comment by grewered** [comment]
I have tried with the "multiple listings" syntax, but that doesn't change the fact, that every article is on one page. 
Now I have tried a custom listing (similar to eat-page). Now we can add links to the new pages, where you can then find a listing for each topic.

to do:

- [ ] create the 5 (for now) new pages with corresponding listings
- [ ] add links to learn page
- [ ] add images to grids

**Comment by grewered** [comment]
So far, the listings on the new linked pages don't work. Maybe you can look into it @nickhaf ?

**Comment by nickhaf** [comment]
closes  #138

**Comment by nickhaf** [comment]
Thanks for the great proposal, I added some stuff and made separate issues for filling in the sub-landing pages (we still have to fill the listings there).

**Pull request merged**
