### PR TITLE
new Newsletter page

### PR DESCRIPTION
**Pull request by grewered**

### CODE REVIEW

**Review by nickhaf — CHANGES_REQUESTED** [review]
Looks great, thanks. Could you also look up two pictures that kind of match the content? I always download from here: https://unsplash.com/de

Please put them into an image folder inside ./newsletter and add them in the yaml with image: ./image/...jpg 

Also put them into the top of the file with Image by [Name on [Unsplash](Link to image on unsplash)](./image/...jpg) 

For the first letter, you could maybe take the eatGADs logo, as the only changes there were in eatGADS.

**Comment by grewered** [comment]
grafik

I don't understand where this error comes from. It started when I added the (png) file image in the yaml header.

**Comment by grewered** [comment]
@nickhaf I was able to render now, but I don't think renv works with me properly, though. But now at least the check has passed.

**Review by nickhaf — APPROVED** [review]
Looks great now, please merge!

**Pull request merged**
